### ISSUE TITLE
회복률 계산을 위한 병렬시뮬레이션 오류

### ISSUE THREAD

**Issue by hnlee77** [fdcl-ftc/fault-tolerant-control#110]
병렬 시뮬레이션을 위해 `modular_test.py`를 이용해서 회복률을 계산하는 시뮬레이션을 수행하던 도중 문제가 발생했습니다.
다음의 고장을 로터에 덮어씌우는 부분에서 오류가 납니다.  이 부분을 지우고 시뮬레이션을 하면 문제가 없는데, 지우지 않은 상태로 시뮬레이션을 하면 아래와 같은 오류가 납니다. 오류 메시지를 보니 concurrent 관련 내용의 이슈인 것 같다는 생각이 듭니다. 그런데 어떻게 해결해야 할 지 전혀 감이 오지않아서 도움을 청해봅니다.
- [bug-concurrent-sim](https://github.com/fdcl-ftc/fault-tolerant-control/tree/bug-concurrent-sim) 브랜치에서 파일을 테스트해볼 수 있습니다.

```
# Set actuator faults                                                   
for act_fault in self.actuator_faults:                                    
    rotors = act_fault(t, rotors)  
```

다음은 오류 메시지입니다.
```
Sample with 24 workers ...
 24%|█████████████████████████████████████████                                                                                                                                  | 24/100 [00:40<02:09,  1.70s/it]
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "test/modular_test.py", line 117, in single_run
    done = env.step()
  File "test/modular_test.py", line 63, in step
    *_, done = self.update()
  File "/mnt/c/Users/hanna/workspace/github/hnlee77/fym/fym/core.py", line 209, in update
    ode_hist = self.solver(
  File "/mnt/c/Users/hanna/workspace/github/hnlee77/fym/fym/core.py", line 482, in rk4
    k1 = func(y[i], t[i], *args)
  File "/mnt/c/Users/hanna/workspace/github/hnlee77/fym/fym/core.py", line 254, in wrapper
    func(t, *args)
  File "test/modular_test.py", line 104, in set_dot
    self.plant.set_dot(t, rotors)
  File "/mnt/c/Users/hanna/workspace/github/fdcl-ftc/fault-tolerant-control/ftc/models/multicopter.py", line 134, in set_dot
    dots = self.deriv(*states, rotors)
  File "/mnt/c/Users/hanna/workspace/github/fdcl-ftc/fault-tolerant-control/ftc/models/multicopter.py", line 117, in deriv
    dvel = g*e3 - F*dcm.T.dot(e3)/m
ValueError: operands could not be broadcast together with shapes (2,1) (3,1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test/modular_test.py", line 159, in <module>
    main()
  File "test/modular_test.py", line 149, in main
    list(tqdm.tqdm(
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/hanna/miniconda3/envs/lab/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (2,1) (3,1)
```

**Comment by seong-hun** [comment]
디버깅을 해보니.. concurrent 모듈이나 다른 문제가 아니라 LoE 클래스가 문제인 것 같네요.. 이전 버전과의 호환성을 위해 좀 더럽게? 짰는데 이게 병렬 계산에서 문제가 되나 봅니다.

**Comment by hnlee77** [comment]
그렇군요.. 혹시 그러면 `LoE` 클래스를 병렬계산과 호환될 수 있도록 바로 수정해주실 수 있을까요?

**Comment by seong-hun** [comment]
이거를 사용법을 유지한채로 바꾸는거는 내가 아직 파이썬이 미숙해서.. 조금 시간이 걸릴것 같은데?

**Comment by hnlee77** [comment]
혹시 그럼 내일까지 가능할까요?

**Comment by seong-hun** [comment]
평일 기준으로 한 4일 정도?

**Comment by hnlee77** [comment]
알겠어요! 가능하면 월요일까지 해주시면 정말 감사하겠습니다 ㅠㅠ

**Comment by seong-hun** [comment]
왜? 급하니? 어디 써야하나?

**Comment by hnlee77** [comment]
네 화요일에 교수님 미팅 예정인데 거기에 시뮬레이션이 들어갔으면 좋겠어서요..

**Comment by seong-hun** [comment]
정 급하면 그냥 따로 LoE 클래스를 만들어서 쓰는 방법도 있어~ 방식 맘대로 해서.. 그럼 급한불은 끌 수 있지 않을까??

**Comment by seong-hun** [comment]
아니면 LoE 클래스 사용법을 바꿀 수 있게 해준다면 내가 빨리 해볼수도 있고..

**Comment by hnlee77** [comment]
사용법을 바꾸게 된다면 함수 인자 같은 것이 바뀌는 걸까요?

**Comment by seong-hun** [comment]
음.. 그냥 fault 클래스 전체적으로 바꿔야할수도?

**Comment by seong-hun** [comment]
초기화라던지 정의하는 방식이라던지

**Comment by hnlee77** [comment]
음.. 계속 문제가 될 수 있으니 사용법이 바뀌어도 괜찮을 것 같아요. 만약 이렇게 변경해서 수정한다면 월요일까지 가능할까요?

**Comment by seong-hun** [comment]
귀찮구먼..ㅋㅋ 빠르게 해볼게

**Comment by hnlee77** [comment]
갓성훈... 진짜로!! 감사합니다ㅋㅋㅋ
