### ISSUE TITLE
CA 동작 이슈

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-ftc/fault-tolerant-control#91]
제가 CA 클래스를 안 쓰는 기법만 써서 동작 방식을 잘 모르는데, 간단한 MWE 에서 오류가 납니다 (어레이 사이즈 오류인듯).
다른 코드에서는 어떻게 동작하고 있죠...?

- test code
```python3
from ftc.agents.CA import CA
from ftc.models.multicopter import Multicopter


if __name__ == "__main__":
    def scope(multicopter, ca):
        print(multicopter.mixer.B)
        print(ca.B)

    multicopter = Multicopter()
    ca = CA(multicopter.mixer.B)
    #
    scope(multicopter, ca)
    fault_index = 1
    value = ca.get(fault_index)
    print(value)
    #
    scope(multicopter, ca)

```

- error msg
```python3
Traceback (most recent call last):
  File "test/test_CA.py", line 15, in <module>
    value = ca.get(fault_index)
  File "/Users/jinrae/github/ftc/fault-tolerant-control/ftc/agents/CA.py", line 29, in get
    self.B[:, fault_index] = np.zeros((4, 1))
ValueError: could not broadcast input array from shape (4,1) into shape (4,)

```

커밋 6740d45 참고 (`test/test_CA.py`)

**Comment by hnlee77** [comment]
`fault_index`를 `[1]`로 수정하면 될것 같아요.
